// Service-worker registration + auto-update / deferred-reload flow (issue #141).
//
// The service worker itself is generated by vite-plugin-pwa (Workbox) and is the
// ONLY place the Cache API is used, and only for the app shell/assets — the
// deliberate, contained exception to CLAUDE.md hard rule #3. This module talks
// only to navigator.serviceWorker; it never touches `caches`, localStorage, or
// any other browser storage directly.
//
// Update strategy (decided in #141): the generated SW ships with skipWaiting +
// clientsClaim, so a newly-installed SW takes control immediately. We do NOT
// reload the page the instant that happens — that would be a disruptive
// mid-interaction reload. Instead we mark the update pending and reload at the
// next *safe* moment: a route change (svelte-spa-router drives the URL hash) or
// the user returning focus to the tab. Reload is data-safe because all real
// state lives in Firestore persistentLocalCache; at worst a transient, untyped
// form field is lost, hence deferring rather than blocking.
//
// A long-open SPA never re-fetches sw.js on its own (route changes don't trigger
// it), so we explicitly poll registration.update() on an interval and on
// refocus — without this a release never reaches an already-open client.

import { isPageReloading, reloadPage } from './pageReload.js';

const SW_URL = '/sw.js';

// ~20 min sits inside the 15–30 min window from #141: frequent enough that an
// open client picks up a release promptly, infrequent enough to be negligible.
const UPDATE_INTERVAL_MS = 20 * 60 * 1000;

export function registerServiceWorker(): void {
  // No SW in dev (HMR + the e2e Vite dev server). Only the production build
  // emits and registers one.
  if (import.meta.env.DEV) return;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;

  window.addEventListener('load', () => {
    navigator.serviceWorker
      // updateViaCache: 'none' so the browser always revalidates sw.js against
      // the network on update checks. Paired with the Firebase Hosting
      // Cache-Control: no-cache header on /sw.js, this closes the stale-SW trap.
      .register(SW_URL, { updateViaCache: 'none' })
      .then(setupUpdateFlow)
      .catch(() => {
        // Registration failure is non-fatal: the app still runs online, it just
        // isn't installable/offline-capable until the next successful load.
      });
  });
}

// One-shot guard for the silent chunk-load auto-reload (Phase 1).
//
// A deploy replaces the hashed chunk files, so an open client that lazy-loads a
// route AFTER a release 404s on the old (now-gone) chunk — Vite surfaces this as
// a `vite:preloadError` window event. The fix is to reload onto the fresh build
// once. We must NOT reload again if the reload itself still hits a preloadError
// (e.g. a genuinely broken deploy), or we'd spin in a reload loop — a later
// phase handles that stuck case. So we set a survives-the-reload flag before
// reloading and refuse to reload again while it is set; it is cleared once the
// app boots successfully (`clearPreloadReloadGuard`, wired from main.ts).
//
// sessionStorage is the right store: the flag must survive the reload within the
// same tab (localStorage would over-persist across unrelated future sessions and
// suppress a legitimate first reload), and it auto-clears when the tab closes.
// Per CLAUDE.md Rule 10 every access is wrapped so storage being unavailable
// degrades quietly and never throws.
const PRELOAD_RELOAD_GUARD_KEY = 'salt:pwa:preloadReloadGuard';

// Exported so the lazy() route wrapper (routes/index.ts, Phase 2) can READ
// whether Phase 1 has already spent its one silent auto-reload this session — a
// read-only guard check, NOT a change to the reload/guard logic. On a persistent
// chunk-load failure it lets the wrapper distinguish "first failure, let Phase 1
// reload" from "already reloaded and still failing, show the inline fallback".
export function hasPreloadReloadGuard(): boolean {
  try {
    return window.sessionStorage.getItem(PRELOAD_RELOAD_GUARD_KEY) !== null;
  } catch {
    // sessionStorage unavailable — treat as "not tripped"; the in-memory latch
    // in setupPreloadErrorReload still prevents a double reload this page load.
    return false;
  }
}

function setPreloadReloadGuard(): void {
  try {
    window.sessionStorage.setItem(PRELOAD_RELOAD_GUARD_KEY, '1');
  } catch {
    /* sessionStorage unavailable — proceed without the surviving-reload guard */
  }
}

// Clear the one-shot guard after a successful boot so the NEXT stale-chunk event
// (a later, separate deploy) is allowed its own single reload. Wired from
// main.ts right after mount.
export function clearPreloadReloadGuard(): void {
  try {
    window.sessionStorage.removeItem(PRELOAD_RELOAD_GUARD_KEY);
  } catch {
    /* ignore */
  }
}

// Silently reload onto the fresh build when a lazy chunk fails to load after a
// deploy — at most once per session (see the guard notes above). No-op in dev
// (Vite serves live modules; there are no hashed prod chunks to go stale),
// mirroring registerServiceWorker's prod-only gating.
export function setupPreloadErrorReload(): void {
  if (import.meta.env.DEV) return;
  if (typeof window === 'undefined') return;

  window.addEventListener('vite:preloadError', () => {
    // In-memory re-entrancy latch, shared with every other programmatic reload
    // (pageReload.ts): once any reload has been asked for, ignore further
    // preloadError events fired before the navigation actually happens.
    if (isPageReloading()) return;
    // Already reloaded once this session and STILL failing — stop here; a later
    // phase surfaces the stuck state.
    if (hasPreloadReloadGuard()) return;
    setPreloadReloadGuard();
    reloadPage();
  });
}

function setupUpdateFlow(registration: ServiceWorkerRegistration): void {
  let updatePending = false;

  // The latch is pageReload.ts's, shared with the stale-chunk and stuck-write
  // reloads, so none of them can double-fire alongside another.
  const reloadIfSafe = (): void => {
    if (!updatePending) return;
    reloadPage();
  };

  // A new SW has installed and (because skipWaiting + clientsClaim) taken
  // control. Only flag it here — do NOT reload now; that is the disruptive
  // mid-interaction reload #141 forbids. The reload happens on the next safe
  // event below.
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    updatePending = true;
  });

  // Safe reload moments.
  // svelte-spa-router navigates via the URL hash, so a route change surfaces as
  // a hashchange — reload there so the new route loads fresh (correctly-hashed)
  // chunks rather than 404-ing against the old build.
  window.addEventListener('hashchange', reloadIfSafe);
  // Returning focus to the tab: first kick an update check (an open background
  // tab may have missed the interval), then reload if an update has landed.
  window.addEventListener('focus', () => {
    void registration.update();
    reloadIfSafe();
  });
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState !== 'visible') return;
    void registration.update();
    reloadIfSafe();
  });

  // Timely update detection for a long-open client.
  setInterval(() => {
    void registration.update();
  }, UPDATE_INTERVAL_MS);
}
